//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedKeyGroup
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public int KeyID { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> KeyOrder { get; set; }
        public bool Statement { get; set; }
        public string DesignType { get; set; }
        public string FirstColumn { get; set; }
        public string AutoNumberStartsFrom { get; set; }
        public string KeyLabel { get; set; }
    }
}
