//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientWiseCustomerTemplate
    {
        public int ClientID { get; set; }
        public int KeyID { get; set; }
        public string KeyName { get; set; }
        public bool Show { get; set; }
    }
}
