//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClouseLog
    {
        public long RowId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long ClouseId { get; set; }
        public string ClouseName { get; set; }
        public string ClouseDescription { get; set; }
        public bool IsEnabled { get; set; }
        public string ModifiedBy { get; set; }
    }
}
