//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoverLetter
    {
        public int CoverLetterId { get; set; }
        public int UserId { get; set; }
        public int GroupId { get; set; }
        public string CustomerName { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
