//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTemplateDetail
    {
        public int id { get; set; }
        public Nullable<int> CustID { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<int> FieldID { get; set; }
        public bool More { get; set; }
        public Nullable<int> ClientID { get; set; }
        public bool Show { get; set; }
    }
}
