//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentSubCategory()
        {
            this.DocumentSubSubCategories = new HashSet<DocumentSubSubCategory>();
        }
    
        public int DocumentSubCategoryId { get; set; }
        public int DocumentCategoryId { get; set; }
        public string DocumentSubCategoryName { get; set; }
        public string SubCategoryDescription { get; set; }
        public bool IsEnabled { get; set; }
        public string ImagePath { get; set; }
    
        public virtual DocumentCategory DocumentCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSubSubCategory> DocumentSubSubCategories { get; set; }
    }
}
