//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentTemplate()
        {
            this.BulkTemplateLogs = new HashSet<BulkTemplateLog>();
        }
    
        public int TemplateId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<decimal> TemplateCost { get; set; }
        public string TemplateFileName { get; set; }
        public int DocumentCategory { get; set; }
        public Nullable<int> DocumentSubCategory { get; set; }
        public Nullable<int> DocumentSubSubCategory { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> AssociateTemplateId { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkTemplateLog> BulkTemplateLogs { get; set; }
    }
}
