//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentDetail()
        {
            this.DocumentStatusChangeRequests = new HashSet<DocumentStatusChangeRequest>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public string Vendor { get; set; }
        public string Purpose { get; set; }
        public System.DateTime DateHanded { get; set; }
        public System.DateTime DateToBeSubmitted { get; set; }
        public int DocumentStatus { get; set; }
        public string RejectionReason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Status { get; set; }
        public int UserId { get; set; }
    
        public virtual DocumentDetailsStatu DocumentDetailsStatu { get; set; }
        public virtual FilledTemplateDetail FilledTemplateDetail { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentStatusChangeRequest> DocumentStatusChangeRequests { get; set; }
    }
}
