//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentCategory()
        {
            this.ClouseandCategoryMapings = new HashSet<ClouseandCategoryMaping>();
            this.DocumentSubCategories = new HashSet<DocumentSubCategory>();
        }
    
        public int DocumentCategoryId { get; set; }
        public string DocumentCategoryDescription { get; set; }
        public string DocumentCategoryName { get; set; }
        public bool IsEnabled { get; set; }
        public int ServiceId { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClouseandCategoryMaping> ClouseandCategoryMapings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSubCategory> DocumentSubCategories { get; set; }
    }
}
