//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DueDiligenceEnquiryType
    {
        public int EnquiryTypeId { get; set; }
        public string EnquiryType { get; set; }
        public bool IsEnabled { get; set; }
    }
}
