//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceId { get; set; }
        public int CustomerId { get; set; }
        public int GroupId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string InvoiceDocumentName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> PaidStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
