//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogKeywordCategory
    {
        public int LogId { get; set; }
        public string Action { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int KeywordCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> CategoryOrder { get; set; }
    }
}
