//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSubSubCategory
    {
        public int LogId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DocumentSubSubCategoryId { get; set; }
        public string SubSubCategoryDescription { get; set; }
        public string SubDocumentCategoryName { get; set; }
        public Nullable<int> DocumentSubCategoryId { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
