//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTemplateUpload
    {
        public int LogId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<decimal> TemplateCost { get; set; }
        public string TemplateFileName { get; set; }
        public Nullable<int> DocumentCategory { get; set; }
        public Nullable<int> DocumentSubCategory { get; set; }
        public Nullable<int> DocumentSubSubCategory { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> AssociateTemplateId { get; set; }
        public Nullable<bool> Mandatory { get; set; }
    }
}
