//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationType
    {
        public int OrganizationTypeId { get; set; }
        public string OrganizationType1 { get; set; }
        public string OrganizationDescription { get; set; }
        public bool IsEnabled { get; set; }
    }
}
