//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int RowId { get; set; }
        public string ApplicationTitle { get; set; }
        public string AdminMailAddress { get; set; }
        public Nullable<int> DueDays { get; set; }
        public string ApplicationUrlEncryptionKey { get; set; }
    }
}
