//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateGroupDetail
    {
        public int id { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string GroupName { get; set; }
        public string DesignType { get; set; }
    }
}
