//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressDetail
    {
        public int RowID { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Designation { get; set; }
        public string StreetName { get; set; }
        public string BuildingName { get; set; }
        public string PlotNumber { get; set; }
        public string BlockNumber { get; set; }
        public string Region { get; set; }
        public string LandMark { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
