//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilledTemplateDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilledTemplateDetail()
        {
            this.Properties = new HashSet<Property>();
            this.DocumentDetails = new HashSet<DocumentDetail>();
        }
    
        public int RowId { get; set; }
        public int UserId { get; set; }
        public int TemplateId { get; set; }
        public string FilledTemplateName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool PaidStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int GroupId { get; set; }
        public Nullable<bool> ArchiveStatus { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<bool> CoverLetter { get; set; }
        public Nullable<int> BulkTemplateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
    }
}
