//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public string Insurer { get; set; }
        public Nullable<decimal> AmountInsured { get; set; }
        public System.DateTime DateOfInsurance { get; set; }
        public System.DateTime DateOfExpiry { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
