//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursiveNotificationDetail
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public Nullable<int> RecurrsBeforeDays { get; set; }
        public Nullable<int> RecurrsAfterDays { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Status { get; set; }
    }
}
