//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.Insurances = new HashSet<Insurance>();
            this.UserAddressDetails = new HashSet<UserAddressDetail>();
            this.ProbationDetails = new HashSet<ProbationDetail>();
            this.DocumentDetails = new HashSet<DocumentDetail>();
        }
    
        public int UserID { get; set; }
        public string EmailAddress { get; set; }
        public bool IsEnabled { get; set; }
        public bool HasActivated { get; set; }
        public bool IsMailSent { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string ReasonForReject { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<bool> TermsConditions { get; set; }
        public Nullable<System.DateTime> UserPasswordLastExpieredOn { get; set; }
        public bool UnusedUser { get; set; }
        public Nullable<int> Department { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance> Insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAddressDetail> UserAddressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProbationDetail> ProbationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
    }
}
