//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationScheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VirtualAdvocateEntities : DbContext
    {
        public VirtualAdvocateEntities()
            : base("name=VirtualAdvocateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<FilledTemplateDetail> FilledTemplateDetails { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserAddressDetail> UserAddressDetails { get; set; }
        public virtual DbSet<DocumentTemplate> DocumentTemplates { get; set; }
        public virtual DbSet<RecursiveNotificationDetail> RecursiveNotificationDetails { get; set; }
        public virtual DbSet<ProbationDetail> ProbationDetails { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<DocumentDetailsStatu> DocumentDetailsStatus { get; set; }
    }
}
